const mockData =  
    [{
    id: 154,
    iten_name: 'Salary',
    amount: 500,
    date: '2023-10-15',
    from_who: 'Employer Inc',
    category: 'Income',
},
{ id: 155,
    iten_name: 'Grocerires',
    amount: 400,
    date: '2023-06-09',
    from_who: 'Employer Inc',
    category: 'Income',
},
{
    id: 176,
    item_name: 'Groceries',
    amount: 500,
    date: '2023-10-20',
    from_who: 'Grocery Store A',
    category: 'Food',
},
{
    id: 287,
    item_name: 'Gasoline',
    amount: 300,
    date: '2023-10-21',
    from_who: 'Gas Station X',
    category: 'Transportation',
},
{
    id: 332,
    item_name: 'Movie Tickets',
    amount: 250,
    date: '2023-10-22',
    from_who: 'Cinema World',
    category: 'Entertainment',
},
{
    id: 172,
    item_name: 'Groceries',
    amount: 50.0,
    date: '2023-10-15',
    from_who: 'Supermart',
    category: 'Food',
},
{
    id: 212,
    item_name: 'Internet Bill',
    amount: 60.0,
    date: '2023-10-16',
    from_who: 'ISP Inc.',
    category: 'Utilities',
},
{
    id: 384,
    item_name: 'Gasoline',
    amount: 30.0,
    date: '2023-10-17',
    from_who: 'Gas Station X',
    category: 'Transportation',
},
{
    id: 153,
    item_name: 'Groceries',
    amount: 50.0,
    date: '2023-10-15',
    from_who: 'Supermart',
    category: 'Food',
},
{
    id: 254,
    item_name: 'Internet Bill',
    amount: 60.0,
    date: '2023-10-16',
    from_who: 'ISP Inc.',
    category: 'Utilities',
},
{
    id: 398,
    item_name: 'Gasoline',
    amount: 30.0,
    date: '2023-10-17',
    from_who: 'Gas Station X',
    category: 'Transportation',
},
{
    id: 465,
    item_name: 'Dinner Out',
    amount: 400,
    date: '2023-10-18',
    from_who: 'Local Restaurant',
    category: 'Food',
},
{
    id: 543,
    item_name: 'Phone Bill',
    amount: 700,
    date: '2023-10-19',
    from_who: 'Telco Corp',
    category: 'Utilities',
},
{
    id: 632,
    item_name: 'Movie Tickets',
    amount: 250,
    date: '2023-10-20',
    from_who: 'Cinema World',
    category: 'Entertainment',
},
{
    id: 765,
    item_name: 'Clothing',
    amount: 800,
    date: '2023-10-21',
    from_who: 'Fashion Store',
    category: 'Shopping',
},
{
    id: 876,
    item_name: 'Taxi Fare',
    amount: 200,
    date: '2023-10-22',
    from_who: 'City Cabs',
    category: 'Transportation',
},
{
    id: 954,
    item_name: 'Groceries',
    amount: 450,
    date: '2023-10-23',
    from_who: 'Supermart',
    category: 'Food',
},
{
    id: 105,
    item_name: 'Gym Membership',
    amount: 550,
    date: '2023-10-24',
    from_who: 'Fitness Center',
    category: 'Health',
},
]
;
 module.exports = mockData;
